### ISSUE TITLE
Uses Textile in help files

### ISSUE THREAD

**Issue by NicolasGraph** [gocom/textpattern-installer#5]
Hi @gocom, 
I recently started to make my plugins available via Composer but I meet the same issue I get during your absence with [MassPlugCompiler](https://github.com/gocom/MassPlugCompiler): help files are not textilized correctly. Id's, Classes and `notextile.` tags are removed, so it breaks many stuff in my styled files. I [forked](https://github.com/NicolasGraph/MassPlugCompiler) your MassPlugCompiler repo in the past to quickly include Textile and also add a mulptile help files support but I'm not sure what could be done with this repo to fix the issue and get a tidy plugin doc. when installed via Composer.

_Edit:_ [This version of oui_player](https://github.com/NicolasGraph/oui_player/releases/tag/1.3.0) can be tested if you need an example; compiled files (via my MassPlugCompiler fork) work nicely but are broken when installed via Composer.

_Edit#2:_ Because I'm not sure why Textpattern does not correctly apply Textile by itself on plugins install, I posted a new [a thread](https://forum.textpattern.io/viewtopic.php?pid=305783#p305783) on the forum.

**Comment by gocom** [comment]
That is because neither the compiler, or the installer, parses the Textile document and converts it to HTML. Instead it lets the Textpattern do it on the install. This is intentional, as I think its better tactic. It's done to:

* avoid having to bundle parser with the Installer nor Compiler.
* to make sure the parser feature set doesn't lock in to what it was on the compile time.
* security and potential ability to for you to preview the documentation safely.

Why parser pears different results for you, is that you and Textpattern are using different parser configuration. Textpattern is using the restricted mode, while you are not. The restricted mode is meant for user-defined input as it sanitizes the given input and makes sure its free of XSS.

**Comment by NicolasGraph** [comment]
Thanks, that's what [I guessed](https://forum.textpattern.io/viewtopic.php?pid=305840#p305840). 'hope I'll find a solution…
